# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  version: 3.7
  system_packages: True 
  install: 
    - requirements: docs_requirements.txt


#conda:
#  environment: conda_env.yml
